apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: amanprakash23/autoscaleml:latest
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_DATABASE
          value: "autoscaleml"
        - name: MYSQL_USER
          value: "user"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_HOST
          value: "mysql"
        - name: MYSQL_PORT
          value: "3306"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000         # Port inside the cluster
      targetPort: 8000   # Port your Django app listens on inside the container
      nodePort: 30080    # External port (Minikube will expose this)
