apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: amanprakash23/autoscaleml:latest
        ports:
        - containerPort: 8000
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          value: "autoscale_db"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "root"
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
  labels:
    app: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
    - port: 8000         # Port inside the cluster
      targetPort: 8000   # Port your Django app listens on inside the container
      nodePort: 30080    # External port (Minikube will expose this)
